# NUMPY

NumPy, short for Numerical Python, is one of the most important pack
ages for numerical computing in PythonNumPy is widely used in data science, machine learning, and scientific computing because of its powerful capabilities for performing mathematical operations on large datasets with minimal code..

## 1.Getting familier with numpy

Numpy stores homogenous data type objects in array

In [2]:
#importing numpy package
import numpy as np

#### Creating a 1D array

In [5]:
#by generating some random data 
data=np.random.randn(6)
data

array([-0.61627244,  0.38502815,  1.15091878,  1.34538903, -2.42347869,
        1.82648333])

In [6]:
#using array function
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

#### Creating a ND array

In [7]:
data2=np.random.randn(2,3)

In [9]:
#(2,3)is the shape of the array
data2

array([[-0.53750081, -0.6129405 , -0.58236439],
       [-0.14249193, -1.31749485,  0.65954959]])

#### Other functions to create arrays

In [17]:
#to create a array of zeroes
zero_arr=np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#to create a array of ones
ones_arr=np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#empty array
empty_arr=np.empty((2,3))
empty_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Array properties

In [12]:
#we can confirm dtype and shape by dtype and shape attributes
data2.dtype

dtype('float64')

In [13]:
data2.shape

(2, 3)

In [14]:
#we can know the dimensions of array by ndim
data2.ndim

2

## Data Manipulation

#### Slicing 

##### 1d array

In [34]:
#create an array
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5]

5

In [37]:
#extracting a part of array
arr[5:8]

array([5, 6, 7])

In [38]:
#manipulating data using slicing
arr[5:8]=12

In [39]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Manipulating data to the entire slice is called broadcasting and we can observe that broadcasting is possible in numpy

In [40]:
slice=arr[5:8]
slice

array([12, 12, 12])

In [43]:
#if i change values in this slice the changes are reflected in original array
slice[1]=456

In [44]:
arr

array([  0,   1,   2,   3,   4,  12, 456,  12,   8,   9])

##### 2d array

In [47]:
#reshape the array using reshape method
arr2=arr.reshape((5,2))
arr2

array([[  0,   1],
       [  2,   3],
       [  4,  12],
       [456,  12],
       [  8,   9]])

In [48]:
#to get the fisrt 2 rows of array
arr2[:2,:]

array([[0, 1],
       [2, 3]])

In [52]:
#to get the fisrt column of first 4rows
arr2[:4,1:]

array([[ 1],
       [ 3],
       [12],
       [12]])

#### Reshaping

In [53]:
arr3=arr2.reshape((2,5))

In [54]:
arr3

array([[  0,   1,   2,   3,   4],
       [ 12, 456,  12,   8,   9]])

In [55]:
data=np.arange(24)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
data2=data.reshape((6,4))
data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Mathematical Operations

In [57]:
#ADDITION OF 2 ARRAYS
data3=data2+data2
data3

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [58]:
#MULTLIPLICATION
data3=data2*data2
data3

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [59]:
#SUBTRACTION
data2-data2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [60]:
#DIVISON
1/data2

C:\Users\MEGHANA\AppData\Local\Temp\ipykernel_32204\2529864702.py:2: RuntimeWarning: divide by zero encountered in divide
  1/data2


array([[       inf, 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.0625    , 0.05882353, 0.05555556, 0.05263158],
       [0.05      , 0.04761905, 0.04545455, 0.04347826]])

In [63]:
#warning is due to first element is 0,lets change using slicing
data2[0][0]=1

In [64]:
1/data2

array([[1.        , 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.0625    , 0.05882353, 0.05555556, 0.05263158],
       [0.05      , 0.04761905, 0.04545455, 0.04347826]])

In [66]:
np.sqrt(data2)

array([[1.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [68]:
data2>data3

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 3.Data Aggregation

In [72]:
arr=np.random.randint(1,100,10)
arr

array([ 3, 64, 50, 73, 81, 25, 92, 45, 84, 58])

In [73]:
#to calculate mean
mean=np.mean(arr)
mean

57.5

In [74]:
#to calculate median
median=np.median(arr)
median

61.0

In [75]:
#to calculate standard deviation
std=np.std(arr)
std

26.39412813487121

In [76]:
#to calculate sum of the elements
sum=np.sum(arr)
sum

575

### 3.Data Analysis

#### Correlations

Correlation measures the relationship between two variables. You can use NumPy's corrcoef() function to compute the correlation coefficient matrix.

In [77]:
data_x = np.random.normal(50, 10, 1000)  # Normally distributed data, mean=50, std=10
data_y = data_x * 0.8 + np.random.normal(0, 5, 1000)  # Correlated data with noise

In [78]:
correlation_matrix = np.corrcoef(data_x, data_y)
correlation_matrix


array([[1.        , 0.84852166],
       [0.84852166, 1.        ]])

#### Outliers

Outliers are data points that differ significantly from other observations. One common method to identify outliers is using the Z-score, which indicates how many standard deviations a data point is from the mean.

Interpretation:
Z = 0: The data point is exactly at the mean.

Z > 0: The data point is above the mean (positive deviation).

Z < 0: The data point is below the mean (negative deviation).

|Z| > 2: Typically indicates that the data point is an outlier, especially if |Z| is greater than 3, meaning it’s very far from the mean.

In [79]:
mean_x = np.mean(data_x)
std_x = np.std(data_x)
z_scores = (data_x - mean_x) / std_x

# Identify outliers
outliers = np.where(np.abs(z_scores) > 3)  # Using a threshold of 3 standard deviations
print("Outliers at indices:", outliers)
print("Outlier values:", data_x[outliers])

Outliers at indices: (array([ 48, 127, 509], dtype=int64),)
Outlier values: [15.48523239 80.19502312 20.28941286]


#### Calculating Percentiles

nth Percentile: The nth percentile is the value below which n percent of the data falls. For example, the 25th percentile is the value below which 25% of the data points are found.

In [80]:
np.percentile(data_x, 25)

43.36902937229056

In [81]:
np.percentile(data_x, 50)

50.19720944126827

In [82]:
np.percentile(data_x, 75)

56.888775801290926

### Efficiency with Large datasets

NumPy is optimized for handling large datasets efficiently. Its operations are vectorized, meaning that operations are applied simultaneously to entire arrays rather than using Python loops. This makes NumPy significantly faster, especially for large-scale computations.

In [87]:
import time

# Large dataset
large_data = np.random.randint(1, 100, 10**7)

# Using NumPy
start_time = time.time()
mean_np = np.mean(large_data)
end_time = time.time()
print("NumPy Mean:", mean_np)
print("NumPy Time:", end_time - start_time)

# Using a Python loop (for comparison)
start_time = time.time()
mean_py = np.sum(large_data) / len(large_data)
end_time = time.time()
print("Python Loop Mean:", mean_py)
print("Python Loop Time:", end_time - start_time)

NumPy Mean: 49.9843259
NumPy Time: 0.009637117385864258
Python Loop Mean: 49.9843259
Python Loop Time: 0.005397796630859375


### Numpy in Datascience

**NumPy** is a powerful tool that enhances the capabilities of data science professionals by providing efficient, scalable, and easy-to-use functionality for numerical computations and data aggregation. Its ability to handle large datasets, perform vectorized operations, and offer a comprehensive set of mathematical and statistical functions makes it far superior to traditional Python data structures. Whether you're calculating basic statistics, performing complex aggregations, or analyzing large-scale data, NumPy is an essential component of the data science toolkit, enabling more effective and efficient data analysis.

## Real world applications

**Machine Learning:** NumPy is vital for data preprocessing, feature scaling, and matrix operations during model training, which are foundational to machine learning.

**Financial Analysis:** NumPy facilitates portfolio optimization, time series analysis, and risk assessment, making it indispensable in finance.

**Scientific Research**:NumPy supports large-scale simulations and statistical analysis, enabling scientists to model complex systems and analyze experimental data efficiently.
In all these areas, NumPy’s ability to handle large datasets, perform efficient mathematical operations, and integrate with other scientific libraries makes it an essential tool, driving advancements in technology, finance, and science.

## SUMMARY

NumPy is a vital tool for data science professionals, offering significant benefits in terms of computational efficiency, data manipulation capabilities, and ease of integration with other libraries. Its ability to handle large datasets, perform complex mathematical operations, and support a wide range of real-world applications makes it an essential component of the data science toolkit. Whether you're working in machine learning, financial analysis, or scientific research, NumPy enables you to process, analyze, and draw insights from data more effectively, ultimately driving better decisions and outcomes in your work.